name: store
description: store

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  json_annotation: 2.0.0
  font_awesome_flutter: 8.4.0
  intl: ^0.15.8

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/12213240-1-multi.jpeg
    - assets/images/1x1.png
    - assets/images/pexels-photo-296881.jpg

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
